// AUTO-GENERATED by scripts/gen-md3-tokens.mjs — do not edit by hand.
// Regenerate with: npm run tokens

export type Md3Role =
  | "primary"
  | "onPrimary"
  | "primaryContainer"
  | "onPrimaryContainer"
  | "secondary"
  | "onSecondary"
  | "secondaryContainer"
  | "onSecondaryContainer"
  | "tertiary"
  | "onTertiary"
  | "tertiaryContainer"
  | "onTertiaryContainer"
  | "error"
  | "onError"
  | "errorContainer"
  | "onErrorContainer"
  | "surface"
  | "onSurface"
  | "onSurfaceVariant"
  | "outline"
  | "outlineVariant"
  | "inverseSurface"
  | "inverseOnSurface"
  | "inversePrimary"
  | "scrim"
  | "surfaceContainerLowest"
  | "surfaceContainerLow"
  | "surfaceContainer"
  | "surfaceContainerHigh"
  | "surfaceContainerHighest"
  | "surfaceDim"
  | "surfaceBright";

export type Md3Scheme = Record<Md3Role, string>;

export const md3 = {
  seed: "#0DB5DB",
  light: {
    roles: {
      primary                : "#00677e",
      onPrimary              : "#ffffff",
      primaryContainer       : "#b5ebff",
      onPrimaryContainer     : "#001f28",
      secondary              : "#4c626a",
      onSecondary            : "#ffffff",
      secondaryContainer     : "#cfe6f0",
      onSecondaryContainer   : "#071e26",
      tertiary               : "#595c7e",
      onTertiary             : "#ffffff",
      tertiaryContainer      : "#e0e0ff",
      onTertiaryContainer    : "#161937",
      error                  : "#ba1a1a",
      onError                : "#ffffff",
      errorContainer         : "#ffdad6",
      onErrorContainer       : "#410002",
      surface                : "#fbfcfe",
      onSurface              : "#191c1d",
      onSurfaceVariant       : "#40484c",
      outline                : "#70787c",
      outlineVariant         : "#bfc8cc",
      inverseSurface         : "#2e3132",
      inverseOnSurface       : "#eff1f2",
      inversePrimary         : "#4ed6fd",
      scrim                  : "#000000",
      surfaceContainerLowest : "#ffffff",
      surfaceContainerLow    : "#f2f4f5",
      surfaceContainer       : "#eceeef",
      surfaceContainerHigh   : "#e7e8ea",
      surfaceContainerHighest: "#e1e3e4",
      surfaceDim             : "#d8dadc",
      surfaceBright          : "#f8f9fb",
    },
    heroui: {
      background: "#fbfcfe",
      foreground: "#191c1d",
      divider: "#bfc8cc",
      overlay: "#000000",
      focus: "#00677e",
      content1: "#ffffff",
      content2: "#f2f4f5",
      content3: "#eceeef",
      content4: "#e7e8ea",
      default: { 50: "#f8f9fb", 100: "#f2f4f5", 200: "#e9ebed", 300: "#dee0e1", 400: "#bfc1c3", 500: "#999b9d", 600: "#7a7c7e", 700: "#616465", 800: "#494c4d", 900: "#323537", foreground: "#191c1d", DEFAULT: "#eceeef" },
      primary: { 50: "#dcf5ff", 100: "#b5ebff", 200: "#4ed6fd", 300: "#1ebae0", 400: "#009ebf", 500: "#00677e", 600: "#004e60", 700: "#003543", 800: "#001f28", 900: "#00131a", foreground: "#ffffff", DEFAULT: "#00677e" },
      secondary: { 50: "#ddf5ff", 100: "#cfe6f0", 200: "#b3cad4", 300: "#98afb8", 400: "#7e949d", 500: "#4c626a", 600: "#344a52", 700: "#1d333b", 800: "#071e26", 900: "#00131a", foreground: "#ffffff", DEFAULT: "#4c626a" },
      success: { 50: "#f6fff0", 100: "#a8fca1", 200: "#92e58c", 300: "#7dce78", 400: "#68b865", 500: "#2E7D32", 600: "#186a22", 700: "#005814", 800: "#00430d", 900: "#003007", foreground: "#FFFFFF", DEFAULT: "#2E7D32" },
      warning: { 50: "#ffefd5", 100: "#ffd174", 200: "#e7bb60", 300: "#cfa54d", 400: "#b8903a", 500: "#7A5900", 600: "#654900", 700: "#513a00", 800: "#3b2900", 900: "#261900", foreground: "#FFFFFF", DEFAULT: "#7A5900" },
      danger: { 50: "#ffedea", 100: "#ffdad6", 200: "#ffb4ab", 300: "#ff897d", 400: "#ff5449", 500: "#ba1a1a", 600: "#93000a", 700: "#690005", 800: "#410002", 900: "#2d0001", foreground: "#ffffff", DEFAULT: "#ba1a1a" },
    },
  },
  dark: {
    roles: {
      primary                : "#4ed6fd",
      onPrimary              : "#003543",
      primaryContainer       : "#004e60",
      onPrimaryContainer     : "#b5ebff",
      secondary              : "#b3cad4",
      onSecondary            : "#1d333b",
      secondaryContainer     : "#344a52",
      onSecondaryContainer   : "#cfe6f0",
      tertiary               : "#c2c3eb",
      onTertiary             : "#2b2e4d",
      tertiaryContainer      : "#424465",
      onTertiaryContainer    : "#e0e0ff",
      error                  : "#ffb4ab",
      onError                : "#690005",
      errorContainer         : "#93000a",
      onErrorContainer       : "#ffb4ab",
      surface                : "#191c1d",
      onSurface              : "#e1e3e4",
      onSurfaceVariant       : "#bfc8cc",
      outline                : "#899296",
      outlineVariant         : "#40484c",
      inverseSurface         : "#e1e3e4",
      inverseOnSurface       : "#2e3132",
      inversePrimary         : "#00677e",
      scrim                  : "#000000",
      surfaceContainerLowest : "#0c0f10",
      surfaceContainerLow    : "#191c1d",
      surfaceContainer       : "#1d2021",
      surfaceContainerHigh   : "#272a2c",
      surfaceContainerHighest: "#323537",
      surfaceDim             : "#111415",
      surfaceBright          : "#373a3b",
    },
    heroui: {
      background: "#191c1d",
      foreground: "#e1e3e4",
      divider: "#40484c",
      overlay: "#000000",
      focus: "#4ed6fd",
      content1: "#0c0f10",
      content2: "#191c1d",
      content3: "#1d2021",
      content4: "#272a2c",
      default: { 50: "#323537", 100: "#494c4d", 200: "#616465", 300: "#7a7c7e", 400: "#999b9d", 500: "#bfc1c3", 600: "#dee0e1", 700: "#e9ebed", 800: "#f2f4f5", 900: "#f8f9fb", foreground: "#e1e3e4", DEFAULT: "#1d2021" },
      primary: { 50: "#ffffff", 100: "#dcf5ff", 200: "#b5ebff", 300: "#87e1ff", 400: "#64daff", 500: "#4ed6fd", 600: "#1ebae0", 700: "#009ebf", 800: "#00829e", 900: "#00677e", foreground: "#003543", DEFAULT: "#4ed6fd" },
      secondary: { 50: "#ffffff", 100: "#ddf5ff", 200: "#cfe6f0", 300: "#c1d8e2", 400: "#b8d0da", 500: "#b3cad4", 600: "#98afb8", 700: "#7e949d", 800: "#647b83", 900: "#4c626a", foreground: "#1d333b", DEFAULT: "#b3cad4" },
      success: { 50: "#00391b", 100: "#005029", 200: "#1a6439", 300: "#31784b", 400: "#468d5e", 500: "#81C995", 600: "#93dca7", 700: "#a6f0b9", 800: "#ddffe2", 900: "#f5fff3", foreground: "#00391C", DEFAULT: "#81C995" },
      warning: { 50: "#5a4300", 100: "#755800", 200: "#8d6a00", 300: "#a57e08", 400: "#bc9323", 500: "#FFCF5C", 600: "#ffe5b2", 700: "#fffbff", 800: "#fffbff", 900: "#fffbff", foreground: "#4A3800", DEFAULT: "#FFCF5C" },
      danger: { 50: "#ffffff", 100: "#ffedea", 200: "#ffdad6", 300: "#ffc7c0", 400: "#ffbcb3", 500: "#ffb4ab", 600: "#ff897d", 700: "#ff5449", 800: "#de3730", 900: "#ba1a1a", foreground: "#690005", DEFAULT: "#ffb4ab" },
    },
  },
  semantic: {
      success: { light: { value: "#2E7D32", on: "#FFFFFF", container: "#A6F4C5", onContainer: "#00210C" }, dark: { value: "#81C995", on: "#00391C", container: "#1B5E2A", onContainer: "#A6F4C5" } },
      warning: { light: { value: "#7A5900", on: "#FFFFFF", container: "#FFDF90", onContainer: "#251A00" }, dark: { value: "#FFCF5C", on: "#4A3800", container: "#614C00", onContainer: "#FFDF90" } },
  },
  typescale: {
    "display-large": { font: "\"Roboto Flex\", sans-serif", weight: 400, size: "3.5625rem", lineHeight: "4rem", tracking: "-0.015625rem" },
    "display-medium": { font: "\"Roboto Flex\", sans-serif", weight: 400, size: "2.8125rem", lineHeight: "3.25rem", tracking: "0rem" },
    "display-small": { font: "\"Roboto Flex\", sans-serif", weight: 400, size: "2.25rem", lineHeight: "2.75rem", tracking: "0rem" },
    "headline-large": { font: "\"Roboto Flex\", sans-serif", weight: 400, size: "2rem", lineHeight: "2.5rem", tracking: "0rem" },
    "headline-medium": { font: "\"Roboto Flex\", sans-serif", weight: 400, size: "1.75rem", lineHeight: "2.25rem", tracking: "0rem" },
    "headline-small": { font: "\"Roboto Flex\", sans-serif", weight: 400, size: "1.5rem", lineHeight: "2rem", tracking: "0rem" },
    "title-large": { font: "\"Roboto Flex\", sans-serif", weight: 400, size: "1.375rem", lineHeight: "1.75rem", tracking: "0rem" },
    "title-medium": { font: "\"Roboto Flex\", sans-serif", weight: 500, size: "1rem", lineHeight: "1.5rem", tracking: "0.009375rem" },
    "title-small": { font: "\"Roboto Flex\", sans-serif", weight: 500, size: "0.875rem", lineHeight: "1.25rem", tracking: "0.00625rem" },
    "body-large": { font: "\"Roboto Flex\", sans-serif", weight: 400, size: "1rem", lineHeight: "1.5rem", tracking: "0.03125rem" },
    "body-medium": { font: "\"Roboto Flex\", sans-serif", weight: 400, size: "0.875rem", lineHeight: "1.25rem", tracking: "0.015625rem" },
    "body-small": { font: "\"Roboto Flex\", sans-serif", weight: 400, size: "0.75rem", lineHeight: "1rem", tracking: "0.025rem" },
    "label-large": { font: "\"Roboto Flex\", sans-serif", weight: 500, size: "0.875rem", lineHeight: "1.25rem", tracking: "0.00625rem" },
    "label-medium": { font: "\"Roboto Flex\", sans-serif", weight: 500, size: "0.75rem", lineHeight: "1rem", tracking: "0.03125rem" },
    "label-small": { font: "\"Roboto Flex\", sans-serif", weight: 500, size: "0.6875rem", lineHeight: "1rem", tracking: "0.03125rem" },
  },
  shape: {"none":"0px","extraSmall":"4px","small":"8px","medium":"12px","large":"16px","extraLarge":"28px","full":"9999px"},
  motion: {"emphasized":"cubic-bezier(0.2, 0, 0, 1)","emphasizedDecelerate":"cubic-bezier(0.05, 0.7, 0.1, 1)","emphasizedAccelerate":"cubic-bezier(0.3, 0, 0.8, 0.15)","standard":"cubic-bezier(0.2, 0, 0, 1)","standardDecelerate":"cubic-bezier(0, 0, 0, 1)","standardAccelerate":"cubic-bezier(0.3, 0, 1, 1)","durationShort":"200ms","durationMedium":"300ms","durationLong":"500ms"},
} as const;

export default md3;
